    SELECT PT.PROD_TYPE, --产品大类
           TMP.PROD_TYPE_CODE,--产品大类Code
           L.ITEM_NAME_CN AS MARKET, --大区
           
           DEPT.DEPT_NAME_CN AS DEPT_NAME,--经营体
           FACTORY.DEPT_NAME_CN AS FACTORY_CODE, --工厂
           TMP.MATERIAL_CODE, --物料
           TMP.HAIER_MODEL, --海尔型号
           TMP.CUSTOMER_MODEL, --客户型号
           TMP.ROLL_RATE, --计划时间
           TMP.START_DATE, --开始时间
           TMP.END_DATE, --结束时间
           TMP.MONTH_DATE,
           TMP.MONTH_N,
           TMP.WEEK_N,
           TMP.WEEK_QUANTITY,
           TMP.R3_DATE,
           TMP.ERROR_DECRIBE,
           TMP.REASON,
           UI.NAME AS PROD_MANAGER_NAME, --产品经理
           SUM(TMP.ACTUAL_QUANTITY) AS ACTUAL_QUANTITY, --滚动计划数量
           SUM(TMP.QUANTITY) AS PREPARE_QUANTITY, --已经销售数量
           SUM(TMP.RATIO_VAL) AS OVERSTEP_QUANTITY,--差异
           CASE
             WHEN SUM(TMP.RATIO_VAL) < SUM(TMP.ACTUAL_QUANTITY) THEN
              ROUND(SUM(TMP.RATIO_VAL) / SUM(TMP.ACTUAL_QUANTITY) * 100, 2)
             WHEN SUM(TMP.RATIO_VAL) = 0 THEN
              0
             WHEN SUM(TMP.RATIO_VAL) >= SUM(TMP.ACTUAL_QUANTITY) THEN
              100
           END AS OVERSTEP_RATE, --离谱率
           CASE
             WHEN SUM(TMP.RATIO_VAL) < SUM(TMP.ACTUAL_QUANTITY) THEN
              ROUND((1 - SUM(TMP.RATIO_VAL) / SUM(TMP.ACTUAL_QUANTITY)) * 100, 2)
             WHEN SUM(TMP.RATIO_VAL) = 0 THEN
              100
             WHEN SUM(TMP.RATIO_VAL) >= SUM(TMP.ACTUAL_QUANTITY) THEN
              0
           END AS ACCURACY_RATE --准确率
    FROM   (SELECT SOR.PROD_TYPE_CODE,
       SOR.MARKET,
       SOR.FACTORY_CODE,
       SOR.MATERIAL_CODE,
       SOR.HAIER_MODEL,
       SOR.CUSTOMER_MODEL,
       SOR.ROLL_RATE,
       SOR.START_DATE,
       SOR.END_DATE,
       SOR.MONTH_DATE,
       SOR.MONTH_N,
       SOR.WEEK_N,
       SUM(SOR.WEEK_QUANTITY) WEEK_QUANTITY,
       SUM(SOR.ACTUAL_QUANTITY) ACTUAL_QUANTITY, --滚动计划数量
       SOR.R3_DATE,
       SOR.ERROR_DECRIBE,
       SOR.REASON,
       SOR.PROD_MANAGER, --产品经理
       SOR.DEPT_CODE, --经营体
       NVL((SELECT SUM(V.QUANTITY)
           FROM   VI_ROLLPLAN_ACT_PREPARE V
           WHERE  V.MATERIAL_CODE = SOR.MATERIAL_CODE
           AND    V.MANU_END_DATE BETWEEN SOR.START_DATE AND SOR.END_DATE
           AND    V.ORDER_PROD_MANAGER = SOR.PROD_MANAGER),
           0) AS QUANTITY, --已经销售数量
       ABS(NVL((SELECT SUM(V.QUANTITY)
               FROM   VI_ROLLPLAN_ACT_PREPARE V
               WHERE  V.MATERIAL_CODE = SOR.MATERIAL_CODE
               AND    V.MANU_END_DATE BETWEEN SOR.START_DATE AND
                      SOR.END_DATE
               AND    V.ORDER_PROD_MANAGER = SOR.PROD_MANAGER),
               0) - SUM(SOR.ACTUAL_QUANTITY)) AS RATIO_VAL
FROM   SI_OES_ROLLPLAN SOR
WHERE  SOR.ROLL_RATE = TO_DATE('2013/12/09', 'yyyy/mm/dd')
AND    SOR.WEEK_N = '3'
GROUP  BY SOR.PROD_TYPE_CODE,
          SOR.MARKET,
          SOR.FACTORY_CODE,
          SOR.MATERIAL_CODE,
          SOR.HAIER_MODEL,
          SOR.CUSTOMER_MODEL,
          SOR.ROLL_RATE,
          SOR.START_DATE,
          SOR.END_DATE,
          SOR.MONTH_DATE,
          SOR.MONTH_N,
          SOR.WEEK_N,
          SOR.R3_DATE,
          SOR.ERROR_DECRIBE,
          SOR.REASON,
          SOR.PROD_MANAGER,
          SOR.DEPT_CODE
UNION
SELECT SSOI.PROD_T_CODE, --产品大类
       SSO.SALE_AREA, --销售大区
       SSO.FACTORY_CODE, --工厂
       SSOI.MATERIAL_CODE, --物料号
       SSOI.HAIER_MODEL, --海尔型号
       SSOI.CUSTOMER_MODEL, --客户型号
       TO_DATE('2013/12/09', 'yyyy/mm/dd'), --滚动计划时间
       WEEK.WEEK_START,
       WEEK.WEEK_END,
       TO_DATE(SUBSTR(TO_CHAR((WEEK.WEEK_START + 2), 'YYYY/MM/DD'), 1, 7) ||
               '/01',
               'yyyy/mm/dd') AS MONTH_DATE,
       SUBSTR(TO_CHAR((WEEK.WEEK_START + 2), 'YYYY/MM/DD'), 6, 2) MONTH_N,
       TO_CHAR(TRUNC((WEEK.WEEK_START - TO_DATE('2013/12/09', 'yyyy/mm/dd')) / 7,
                     0)) WEEK_N,
       0 WEEK_QUANTITY,
       0 ACTUAL_QUANTITY, --滚动计划数量
       NULL R3_DATE,
       '' ERROR_DECRIBE,
       '' REASON,
       SSO.ORDER_PROD_MANAGER AS PROD_MANAGER, --产品经理
       SSO.DEPT_CODE, --经营体
       APOI.QUANTITY AS QUANTITY, --已经销售数量
       APOI.QUANTITY AS RATIO_VAL
FROM   SO_SALES_ORDER_ITEM    SSOI,
       ACT_PREPARE_ORDER_ITEM APOI,
       ACT_PREPARE_ORDER      APO,
       SO_SALES_ORDER         SSO,
       V_WEEK_Y               WEEK
WHERE  1 = 1
AND    SSOI.ORDER_ITEM_ID = APOI.ORDER_ITEM_ID
AND    APOI.ACT_PREPARE_ORDER_CODE = APO.ACT_PREPARE_CODE
AND    SSO.ORDER_CODE = SSOI.ORDER_CODE
AND    APO.ORDER_NUM = SSO.ORDER_CODE
AND    APO.MANU_END_DATE BETWEEN WEEK.WEEK_START AND WEEK.WEEK_END
AND    TO_CHAR(TRUNC((WEEK.WEEK_START -
                     TO_DATE('2013/12/09', 'yyyy/mm/dd')) / 7,
                     0)) BETWEEN '3' AND '3'
AND    NOT EXISTS
 (SELECT *
        FROM   SI_OES_ROLLPLAN SOR
        WHERE  SOR.START_DATE = WEEK.WEEK_START
        AND    SOR.END_DATE = WEEK.WEEK_END
        AND    SOR.FACTORY_CODE = APO.FACTORY_PRODUCE_CODE
        AND    SOR.PROD_MANAGER = SSO.ORDER_PROD_MANAGER
        AND    APOI.MATERIAL_CODE = SOR.MATERIAL_CODE)
UNION
SELECT SSOI.PROD_T_CODE, --产品大类
       SSO.SALE_AREA, --销售大区
       SSO.FACTORY_CODE, --工厂
       SSOI.MATERIAL_CODE, --物料号
       SSOI.HAIER_MODEL, --海尔型号
       SSOI.CUSTOMER_MODEL, --客户型号
       TO_DATE('2013/12/09', 'yyyy/mm/dd'), --滚动计划时间
       WEEK.WEEK_START,
       WEEK.WEEK_END,
       TO_DATE(SUBSTR(TO_CHAR((WEEK.WEEK_START + 2), 'YYYY/MM/DD'), 1, 7) ||
               '/01',
               'yyyy/mm/dd') AS MONTH_DATE,
       SUBSTR(TO_CHAR((WEEK.WEEK_START + 2), 'YYYY/MM/DD'), 6, 2) MONTH_N,
       TO_CHAR(TRUNC((WEEK.WEEK_START - TO_DATE('2013/12/09', 'yyyy/mm/dd')) / 7,
                     0)) WEEK_N,
       0 WEEK_QUANTITY,
       0 ACTUAL_QUANTITY, --滚动计划数量
       NULL R3_DATE,
       '' ERROR_DECRIBE,
       '' REASON,
       SSO.ORDER_PROD_MANAGER AS PROD_MANAGER, --产品经理
       SSO.DEPT_CODE, --经营体
       APOI.QUANTITY AS QUANTITY, --已经销售数量
       APOI.QUANTITY AS RATIO_VAL
FROM   SO_SALES_ORDER_ITEM    SSOI,
       ACT_PREPARE_ORDER_ITEM APOI,
       ACT_PREPARE_ORDER      APO,
       SO_SALES_ORDER         SSO,
       V_WEEK_Y               WEEK
WHERE  1 = 1
AND    SSOI.ORDER_ITEM_ID = APOI.ORDER_ITEM_ID
AND    APOI.ACT_PREPARE_ORDER_CODE = APO.ACT_PREPARE_CODE
AND    SSO.ORDER_CODE = SSOI.ORDER_CODE
AND    APO.ORDER_NUM = SSO.ORDER_CODE
AND    APO.MANU_END_DATE BETWEEN WEEK.WEEK_START AND WEEK.WEEK_END
AND    TO_CHAR(TRUNC((WEEK.WEEK_START -
                     TO_DATE('2013/12/09', 'yyyy/mm/dd')) / 7,
                     0)) BETWEEN '3' AND '3'
AND    NOT EXISTS
 (SELECT *
        FROM   SI_OES_ROLLPLAN SOR
        WHERE  SOR.START_DATE = WEEK.WEEK_START
        AND    SOR.END_DATE = WEEK.WEEK_END
        AND    SSO.ORDER_PROD_MANAGER = SOR.PROD_MANAGER)
UNION
SELECT SSOI.PROD_T_CODE, --产品大类
       SSO.SALE_AREA, --销售大区
       SSO.FACTORY_CODE, --工厂
       SSOI.MATERIAL_CODE, --物料号
       SSOI.HAIER_MODEL, --海尔型号
       SSOI.CUSTOMER_MODEL, --客户型号
       TO_DATE('2013/12/09', 'yyyy/mm/dd'), --滚动计划时间
       WEEK.WEEK_START,
       WEEK.WEEK_END,
       TO_DATE(SUBSTR(TO_CHAR((WEEK.WEEK_START + 2), 'YYYY/MM/DD'), 1, 7) ||
               '/01',
               'yyyy/mm/dd') AS MONTH_DATE,
       SUBSTR(TO_CHAR((WEEK.WEEK_START + 2), 'YYYY/MM/DD'), 6, 2) MONTH_N,
       TO_CHAR(TRUNC((WEEK.WEEK_START - TO_DATE('2013/12/09', 'yyyy/mm/dd')) / 7,
                     0)) WEEK_N,
       0 WEEK_QUANTITY,
       0 ACTUAL_QUANTITY, --滚动计划数量
       NULL R3_DATE,
       '' ERROR_DECRIBE,
       '' REASON,
       SSO.ORDER_PROD_MANAGER AS PROD_MANAGER, --产品经理
       SSO.DEPT_CODE, --经营体
       APOI.QUANTITY AS QUANTITY, --已经销售数量
       APOI.QUANTITY AS RATIO_VAL
FROM   SO_SALES_ORDER_ITEM    SSOI,
       ACT_PREPARE_ORDER_ITEM APOI,
       ACT_PREPARE_ORDER      APO,
       SO_SALES_ORDER         SSO,
       V_WEEK_Y               WEEK
WHERE  1 = 1
AND    SSOI.ORDER_ITEM_ID = APOI.ORDER_ITEM_ID
AND    APOI.ACT_PREPARE_ORDER_CODE = APO.ACT_PREPARE_CODE
AND    SSO.ORDER_CODE = SSOI.ORDER_CODE
AND    APO.ORDER_NUM = SSO.ORDER_CODE
AND    APO.MANU_END_DATE BETWEEN WEEK.WEEK_START AND WEEK.WEEK_END
AND    TO_CHAR(TRUNC((WEEK.WEEK_START -
                     TO_DATE('2013/12/09', 'yyyy/mm/dd')) / 7,
                     0)) BETWEEN '3' AND '3'
AND    NOT EXISTS
 (SELECT *
        FROM   SI_OES_ROLLPLAN SOR
        WHERE  SOR.START_DATE = WEEK.WEEK_START
        AND    SOR.END_DATE = WEEK.WEEK_END
        AND    SOR.PROD_MANAGER = SSO.ORDER_PROD_MANAGER
        AND    APO.FACTORY_PRODUCE_CODE = SOR.FACTORY_CODE)) TMP
		LEFT   JOIN CD_PROD_TYPE PT
		ON     PT.PROD_TYPE_CODE = TMP.PROD_TYPE_CODE
		LEFT   JOIN SYS_LOV L
		ON     ( L.ITEM_CODE = TMP.MARKET AND l.item_type='3')
		
		LEFT   JOIN USER_INFO UI
		ON     UI.EMP_CODE = TMP.PROD_MANAGER
		LEFT   JOIN CD_DEPARTMENT DEPT
		ON     DEPT.DEPT_CODE = TMP.DEPT_CODE
		LEFT   JOIN CD_DEPARTMENT FACTORY
		ON     FACTORY.DEPT_CODE = TMP.FACTORY_CODE
    GROUP BY TMP.MATERIAL_CODE,PT.PROD_TYPE,
		L.ITEM_NAME_CN,FACTORY.DEPT_NAME_CN, TMP.PROD_TYPE_CODE,
		TMP.HAIER_MODEL,TMP.CUSTOMER_MODEL,TMP.ROLL_RATE,
		TMP.START_DATE,TMP.END_DATE,TMP.MONTH_DATE,
		TMP.MONTH_N,TMP.WEEK_N,TMP.WEEK_QUANTITY,
		TMP.R3_DATE,TMP.ERROR_DECRIBE,
		TMP.REASON, UI.NAME, DEPT.DEPT_NAME_CN
