SELECT DISTINCT PO.ACT_PREPARE_CODE, -- 备货单号   
                PO.ORDER_NUM, --订单号   
                SO.CONTRACT_CODE, -- 合同号  
                C.NAME, --出口国家      
                PO.CHECK_CODE, --商检批次号               
                PO.FIRST_SAMPLE_DATE, --首样开始时间  
                PO.MANU_START_DATE, --生产计划开始    
                PO.PACKING_START_DATE, --装箱计划开始    
                PO.CHECK_START_DATE, --商检计划开始  
                PO.MANU_END_DATE, --生产计划结束    
                PO.PACKING_END_DATE, --装箱计划开始    
                PO.CHECK_END_DATE, --商检计划开始    
                CUST.NAME AS CUSTNAME, --客户     
                DT.DEPT_NAME_CN AS DEPTNAME, --经营主体    
                DECODE(SO.ORDER_BUYOUT_FLAG, '0', '否', '1', '是') AS ORDER_BUYOUT_FLAG, --是否买断  
                LO.ITEM_NAME_CN AS SALES_ORG_NAME, --销售组织    
                L.ITEM_NAME_CN AS SALES_CHENNEL, --销售渠道    
                DECODE(PO.SETTLEMENT_TYPE, '0', '代理', '1', '收购') AS ORDER_SETTLEMENT_TYPE, --结算方式      
                PO.FACTORY_PRODUCE_CODE || FACTORY.DEPT_NAME_CN AS FACTORYPRODUCENAME, --生产工厂    
                PO.FACTORY_SETTLEMENT_CODE || FACTORYT.DEPT_NAME_CN AS FACTORY_SETTLEMENT_NAME, --结算工厂
                SO.ORDER_SHIP_DATE, --出运时间
                POI.ORDER_ITEM_ID AS ORDER_LINECODE, --行项目号
                PT.PROD_TYPE, --产品大类
                SOI.HAIER_MODEL, --海尔型号
                SOI.CUSTOMER_MODEL, --客户型号
                SOI.AFFIRM_NUM, --特技单好
                POI.MATERIAL_CODE, --BOM号
                POI.QUANTITY, --数量
                ORDERTYPE.ITEM_NAME_CN ORDER_TYPE, --订单类型
                PO.CREATED,
                SO.ORDER_AUDIT_DATE ACTUAL_FINISH_DATE
FROM   ACT_PREPARE_ORDER PO
JOIN   ACT_PREPARE_ORDER_ITEM POI
ON     PO.ACT_PREPARE_CODE = POI.ACT_PREPARE_ORDER_CODE
LEFT   JOIN SO_SALES_ORDER SO
ON     PO.ORDER_NUM = SO.ORDER_CODE
JOIN   SO_SALES_ORDER_ITEM SOI
ON     (SOI.ORDER_CODE = PO.ORDER_NUM AND
       POI.MATERIAL_CODE = SOI.MATERIAL_CODE)
LEFT   JOIN CD_PROD_TYPE PT
ON     PT.PROD_TYPE_CODE = SOI.PROD_T_CODE
LEFT   JOIN SYS_LOV L
ON     (PO.SALES_CHENNEL = L.ITEM_CODE AND L.ITEM_TYPE = '20')
LEFT   JOIN SYS_LOV LO
ON     (LO.ITEM_CODE = PO.SALES_ORG_CODE AND LO.ITEM_TYPE = '21')
LEFT   JOIN CD_DEPARTMENT DT
ON     (SO.DEPT_CODE = DT.DEPT_CODE AND DT.DEPT_TYPE = '1')
LEFT   JOIN CD_CUSTOMER CUST
ON     SO.ORDER_SOLD_TO = CUST.CUSTOMER_CODE
LEFT   JOIN CD_COUNTRY C
ON     SO.COUNTRY_CODE = C.COUNTRY_CODE
LEFT   JOIN CD_DEPARTMENT FACTORY
ON     (FACTORY.DEPT_CODE = PO.FACTORY_PRODUCE_CODE AND
       FACTORY.DEPT_TYPE = '0')
LEFT   JOIN CD_DEPARTMENT FACTORYT
ON     (FACTORYT.DEPT_CODE = PO.FACTORY_SETTLEMENT_CODE AND
       FACTORYT.DEPT_TYPE = '0')
LEFT   JOIN SYS_LOV ORDERTYPE
ON     (ORDERTYPE.ITEM_CODE = SO.ORDER_TYPE AND ORDERTYPE.ITEM_TYPE = '0')
WHERE  PO.ORDER_NUM = #{ORDERNUM}
ORDER  BY PO.ACT_PREPARE_CODE
