SELECT PO.ACT_PREPARE_CODE, -- 备货单号   
       PO.ORDER_NUM, --订单号   
       SO.CONTRACT_CODE, -- 合同号  
       C.NAME, --出口国家    
       '是' AS ROSH, --ROSH     
       PO.CHECK_CODE, --商检批次号           
       PO.HGVS_ORDER_CODE AS ORDER_HGVS_CODE, --HGVS订单号      
       PO.FIRST_SAMPLE_DATE, --首样开始时间  
       PO.MANU_START_DATE, --生产计划开始    
       PO.PACKING_START_DATE, --装箱计划开始    
       PO.CHECK_START_DATE, --商检计划开始  
       PO.MANU_END_DATE, --生产计划结束    
       PO.PACKING_END_DATE, --装箱计划开始    
       PO.CHECK_END_DATE, --商检计划开始    
       CUST.NAME AS CUSTNAME, --客户     
       DT.DEPT_NAME_CN AS DEPTNAME, --经营主体    
       DECODE(SO.ORDER_BUYOUT_FLAG, '0', '否', '1', '是') AS ORDER_BUYOUT_FLAG, --是否买断  
       LO.ITEM_NAME_CN AS SALES_ORG_NAME, --销售组织    
       L.ITEM_NAME_CN AS SALES_CHENNEL, --销售渠道    
       DECODE(PO.SETTLEMENT_TYPE, '0', '代理', '1', '收购') AS ORDER_SETTLEMENT_TYPE, --结算方式      
       PO.FACTORY_PRODUCE_CODE AS FACTORYPRODUCENAME, --生产工厂    
       PO.FACTORY_SETTLEMENT_CODE AS FACTORY_SETTLEMENT_NAME, --结算工厂
       SO.ORDER_SHIP_DATE --出运时间
FROM   ACT_PREPARE_ORDER PO
LEFT   JOIN SO_SALES_ORDER SO
ON     PO.ORDER_NUM = SO.ORDER_CODE
LEFT   JOIN CD_COUNTRY C
ON     SO.COUNTRY_CODE = C.COUNTRY_CODE
LEFT   JOIN CD_CUSTOMER CUST
ON     SO.ORDER_SOLD_TO = CUST.CUSTOMER_CODE
LEFT   JOIN CD_DEPARTMENT DT
ON     SO.DEPT_CODE = DT.DEPT_CODE
LEFT   JOIN CD_DEPARTMENT DTF
ON     DTF.DEPT_CODE = PO.FACTORY_PRODUCE_CODE
LEFT   JOIN CD_DEPARTMENT DTFS
ON     DTFS.DEPT_CODE = PO.FACTORY_SETTLEMENT_CODE
LEFT   JOIN SYS_LOV L
ON     (PO.SALES_CHENNEL = L.ITEM_CODE AND L.ITEM_TYPE = '20')
LEFT   JOIN SYS_LOV LO
ON     (LO.ITEM_CODE = PO.SALES_ORG_CODE AND LO.ITEM_TYPE = '21')
