SELECT EXECUTION.ID_           AS EXECUTION_ID,
       TASK.ID_                AS TASK_ID,
       WF.*,
       L.ITEM_NAME_CN          AS ORDER_TYPE_NAME,
       S.ORDER_CODE,
       S.ORDER_TYPE,
       S.ORDER_PO_CODE,
       S.ORDER_SETTLEMENT_TYPE,
       D.DEPT_NAME_CN          AS DEPT_NAME,
       C.NAME                  AS COUNTRY_NAME,
       U.NAME                  AS PROD_MANAGER,
       CU.NAME                 AS CUSTOMER_NAME
FROM   ACT_RU_EXECUTION EXECUTION
LEFT   JOIN ACT_RU_TASK TASK
ON     EXECUTION.ID_ = TASK.EXECUTION_ID_
LEFT   JOIN WF_PROCINSTANCE WF
ON     EXECUTION.PROC_INST_ID_ = WF.PROCESSINSTANCE_ID
LEFT   JOIN SO_SALES_ORDER S
ON     WF.BUSINFORM_ID = S.ORDER_CODE
LEFT   JOIN SYS_LOV L
ON     (S.ORDER_TYPE = L.ITEM_CODE AND L.ITEM_TYPE = '0')
LEFT   JOIN CD_DEPARTMENT D
ON     S.DEPT_CODE = D.DEPT_CODE
LEFT   JOIN CD_COUNTRY C
ON     S.COUNTRY_CODE = C.COUNTRY_CODE
LEFT   JOIN USER_INFO U
ON     S.ORDER_PROD_MANAGER = U.EMP_CODE
LEFT   JOIN CD_CUSTOMER CU
ON     S.ORDER_SOLD_TO = CU.CUSTOMER_CODE
WHERE  EXECUTION.ACT_ID_ = 'getNegoInfoFromHope'
ORDER  BY S.ORDER_CODE ASC
