SELECT DISTINCT PO.ORDER_NUM,
                SO.ORDER_PO_CODE,
                PO.HGVS_ORDER_CODE AS ORDER_HGVS_CODE,
                SO.CONTRACT_CODE,
                CUST.NAME AS CUSTNAME,
                LO.SALE_ORG_NAME AS SALES_ORG_NAME,
                L.ITEM_NAME_CN AS SALES_CHENNEL,
                PO.CHECK_CODE,
                PO.ACT_PREPARE_CODE,
                PT.PROD_TYPE,
                DT.DEPT_NAME_CN,
                CY.NAME,
                DTT.DEPT_NAME_CN AS DEPT_CODE,
                CYUI.NAME AS MANAGER_NAME,
                PO.CREATED,
                PO.MANU_END_DATE,
                SOI.HAIER_MODEL,
                SOI.CUSTOMER_MODEL,
                SOI.AFFIRM_NUM,
                -SOI.MATERIAL_CODE,
                POI.QUANTITY,
                PO.FIRST_SAMPLE_DATE,
                SO.ORDER_SHIP_DATE,
                PO.PACKING_START_DATE,
                PO.PACKING_END_DATE,
                PO.MANU_START_DATE,
                PO.CHECK_START_DATE,
                PO.CHECK_END_DATE,
                SUM(HPT.ORDER_FINISHED_COUNT) ORDER_FINISHED_COUNT,
                ACT.ACTUAL_FINISH_DATE,
                ACTSCH.ACTUAL_FINISH_DATE AS SCH_FINISH_DATE,
                ACTPAY.ACTUAL_FINISH_DATE AS PAY_FINISH_DATE,
                BSP.BOOK_SHIP_DATE,
                SO.SPECIAL_INSPECTION
  FROM ACT_PREPARE_ORDER PO
  JOIN ACT_PREPARE_ORDER_ITEM POI
    ON PO.ACT_PREPARE_CODE = POI.ACT_PREPARE_ORDER_CODE
  JOIN SO_SALES_ORDER SO
    ON (PO.ORDER_NUM = SO.ORDER_CODE AND SO.ORDER_AUDIT_FLAG <> 2)
  JOIN SO_SALES_ORDER_ITEM SOI
    ON (SOI.ORDER_CODE = PO.ORDER_NUM AND
       POI.MATERIAL_CODE = SOI.MATERIAL_CODE)
  LEFT JOIN CD_COUNTRY CY
    ON SO.COUNTRY_CODE = CY.COUNTRY_CODE
  LEFT JOIN USER_INFO CYUI
    ON CYUI.EMP_CODE = SO.Order_Prod_Manager
  LEFT JOIN CD_PROD_TYPE PT
    ON PT.PROD_TYPE_CODE = SOI.PROD_T_CODE
  LEFT JOIN CD_DEPARTMENT DT
    ON DT.DEPT_CODE = PO.FACTORY_PRODUCE_CODE
  LEFT JOIN CD_DEPARTMENT DTT
    ON DTT.DEPT_CODE = PO.DEPT_CODE
   AND DTT.dept_type = '1'
  LEFT JOIN CD_CUSTOMER CUST
    ON SO.ORDER_SOLD_TO = CUST.CUSTOMER_CODE
  LEFT JOIN SYS_LOV L
    ON PO.SALES_CHENNEL = L.ITEM_CODE
  LEFT JOIN CD_SALE_ORG LO
    ON LO.SALE_ORG_CODE = PO.SALES_ORG_CODE
  LEFT JOIN SI_HGVS_PO_TRACK HPT
    ON (HPT.PREPARE_CODE = PO.ACT_PREPARE_CODE AND
       HPT.MATERIAL_CODE = POI.MATERIAL_CODE AND
       HPT.TRACK_FINISHED_FLAG = '1')
  LEFT JOIN SO_ACT ACT
    ON (SO.ORDER_CODE = ACT.ORDER_NUM AND
       ACT.ACT_ID = 'businessManagerSalesOrder')
  LEFT JOIN SO_ACT ACTSCH
    ON (SO.ORDER_CODE = ACTSCH.ORDER_NUM AND ACTSCH.ACT_ID = 'scheduling')
  LEFT JOIN SO_ACT ACTPAY
    ON (SO.ORDER_CODE = ACTPAY.ORDER_NUM AND ACTPAY.ACT_ID = 'payMoney#')
  LEFT JOIN SO_ACT ACTSUB
    ON (SO.ORDER_CODE = ACTSUB.ORDER_NUM AND
       ACTSUB.ACT_ID = 'subProcessNego')
  LEFT JOIN (SELECT SP.BOOK_SHIP_DATE, BOI.ORDER_CODE, BOI.ORDER_ITEM_CODE
               FROM ACT_BOOK_ORDER_ITEM BOI, ACT_SHIP_PAPER SP
              WHERE SP.BOOK_CODE = BOI.BOOK_CODE) BSP
    ON (BSP.ORDER_CODE = PO.ORDER_NUM AND
       BSP.ORDER_ITEM_CODE = SOI.ORDER_ITEM_LINECODE)
 WHERE 1 = 1
   AND PO.FACTORY_PRODUCE_CODE IN
       (SELECT t0.CONFIG_VALUE AS CONFIG_VALUE
          FROM hrois.USER_DATA_CONFIG t0
         WHERE (t0.EMPLOYEE_CODE = 'admin' AND t0.CONFIG_TYPE = 'FACTORY'))
   AND PO.ORDER_NUM LIKE '0004306466'
 GROUP BY PO.ORDER_NUM,
          SO.ORDER_PO_CODE,
          PO.HGVS_ORDER_CODE,
          SO.CONTRACT_CODE,
          CUST.NAME,
          LO.SALE_ORG_NAME,
          L.ITEM_NAME_CN,
          PO.CHECK_CODE,
          PO.ACT_PREPARE_CODE,
          PT.PROD_TYPE,
          DT.DEPT_NAME_CN,
          CY.NAME,
          PO.CREATED,
          PO.MANU_END_DATE,
          SOI.HAIER_MODEL,
          SOI.CUSTOMER_MODEL,
          SOI.AFFIRM_NUM,
          SOI.MATERIAL_CODE,
          POI.QUANTITY,
          PO.FIRST_SAMPLE_DATE,
          SO.ORDER_SHIP_DATE,
          PO.PACKING_START_DATE,
          PO.PACKING_END_DATE,
          PO.MANU_START_DATE,
          PO.CHECK_START_DATE,
          PO.CHECK_END_DATE,
          ACT.ACTUAL_FINISH_DATE,
          ACTSCH.ACTUAL_FINISH_DATE,
          ACTPAY.ACTUAL_FINISH_DATE,
          DTT.DEPT_NAME_CN,
          CYUI.NAME,
          BSP.BOOK_SHIP_DATE,
          SPECIAL_INSPECTION,
          HPT.TRACK_TYPE
 ORDER BY PO.ORDER_NUM, PO.ACT_PREPARE_CODE
 
--C1320BH08033US
 select * from SI_HGVS_PO_TRACK a  where a.prepare_code = 'G0520BH90056IQ' --for update
 select  *from ACT_PREPARE_ORDER b where b.order_num = '0004319239'
 
