SELECT DISTINCT SO.ORDER_CODE, --订单号
                SO.CONTRACT_CODE, --合同号
                ORDERTYPE.ITEM_NAME_CN ORDER_TYPE, --订单类型
                SO.ORDER_AUDIT_FLAG    RFLAG, --状态
                CUST.NAME              CUSTNAME, --客户
                CT.NAME                COUNTRY_NAME, --国家
                SO.ORDER_SHIP_DATE, --出运期
                SHIPMENT.ITEM_NAME_CN  SHIP_TO, --运输方式
                EXECM.NAME             ORDER_EXEC_MANAGER, --订单执行经理
                CUSTM.NAME             ORDER_CUST_NAMAGER, --经营体长
                PT.PROD_TYPE, --产品大类
                SOI.HAIER_MODEL, --海尔型号
                SOI.CUSTOMER_MODEL, --客户型号
                SOI.AFFIRM_NUM, --特技单号
                SOI.MATERIAL_CODE, --物料号
                DT.DEPT_NAME_CN        DEPT_NAME_CN, --生产工厂
                SOI.PROD_QUANTITY, --数量
                SOI.PRICE, --单价
                SO.ORDER_AUDIT_DATE    ACTUAL_FINISH_DATE
FROM   SO_SALES_ORDER SO
JOIN   SO_SALES_ORDER_ITEM SOI
ON     SO.ORDER_CODE = SOI.ORDER_CODE
LEFT   JOIN SYS_LOV ORDERTYPE
ON     (ORDERTYPE.ITEM_TYPE = '0' AND ORDERTYPE.ITEM_CODE = SO.ORDER_TYPE)
LEFT   JOIN CD_CUSTOMER CUST
ON     CUST.CUSTOMER_CODE = SO.ORDER_SOLD_TO
LEFT   JOIN CD_COUNTRY CT
ON     CT.COUNTRY_CODE = SO.COUNTRY_CODE
LEFT   JOIN SYS_LOV SHIPMENT
ON     (SHIPMENT.ITEM_TYPE = '7' AND SHIPMENT.ITEM_CODE = SO. ORDER_SHIPMENT)
LEFT   JOIN CD_DEPARTMENT DT
ON     (DT.DEPT_TYPE = '0' AND DT.DEPT_CODE = SOI.FACTORY_CODE)
LEFT   JOIN CD_PROD_TYPE PT
ON     PT.PROD_TYPE_CODE = SOI.PROD_T_CODE
LEFT   JOIN USER_INFO EXECM
ON     EXECM.EMP_CODE = SO.ORDER_EXEC_MANAGER
LEFT   JOIN USER_INFO CUSTM
ON     CUSTM.EMP_CODE = SO.ORDER_CUST_NAMAGER
LEFT   JOIN ACT_PREPARE_ORDER PO
ON     SO.ORDER_CODE = PO.ORDER_NUM
WHERE  PO.ORDER_NUM IS NULL
AND    (SO.ORDER_AUDIT_FLAG = '0' OR SO.ORDER_AUDIT_FLAG = '1')
AND    SO.ORDER_TYPE != '5'
AND    SO.ORDER_TYPE != '6'
AND    SO.ORDER_TYPE != '9'
