SELECT *
FROM   SO_ACT C
WHERE  C.ORDER_NUM IN (SELECT P.ORDER_NUM
                       FROM   ACT_PREPARE_ORDER P
                       WHERE  P.HGVS_ORDER_CODE IS NOT NULL)
AND    C.ACTUAL_FINISH_DATE IS NULL
AND    C.ACT_ID = 'exportHGVS'
