--工作流不正常导致的报错
SELECT ROW_ID,
       PROCESSINSTANCE_ID,
       PROCESSDEFINITION_KEY,
       BUSINFORM_ID,
       BUSINFORM_TYPE,
       status
  FROM WF_PROCINSTANCE
 WHERE PROCESSDEFINITION_KEY like 'orderTrace' || '%'
   AND BUSINFORM_ID = '0004308444'
   AND BUSINFORM_TYPE = 'SO_SALES_ORDER'
   AND STATUS = '0'
for update
