--≤È—Ø∂©µ•       
SELECT BOOK_CODE  FROM ACT_BOOK_ORDER_ITEM where ORDER_CODE  = '0004292992';


SELECT PI.*,
       OI.*
  FROM ACT_SHIP_PAPER_ITEM PI
  LEFT JOIN SO_SALES_ORDER_ITEM OI
    ON (PI.ORDER_CODE = OI.ORDER_CODE and
       PI.ORDER_ITEM_LINE_CODE = OI.ORDER_ITEM_LINECODE)
 WHERE PI.SHIP_PAPER_ROW_ID =
       (SELECT SP.ROW_ID FROM ACT_SHIP_PAPER SP WHERE SP.BOOK_CODE ='2020090101072544')

SELECT * FROM ACT_SHIP_PAPER SP WHERE SP.BOOK_CODE ='2020090101072544' for update
SELECT * FROM Act_Ship_Paper_Item SPI WHERE SPI.Ship_Paper_Row_Id ='2020090100929517'
