SELECT SO.ORDER_CODE, --订单号   
       D.OPERATORS, --经营主体  
       SOI.MATERIAL_CODE, --产品名称  
       SOI.PROD_QUANTITY, --订单数量   
       SO.ORDER_DEAL_TYPE,
       CASE
         WHEN SO.ORDER_DEAL_TYPE IN ('FOB', 'CIF', 'CFR') THEN
          SOI.AMOUNT
         WHEN SO.ORDER_DEAL_TYPE IN ('FWF', 'FTC', 'FFI') THEN
          SOI.AMOUNT + (SOI.AMOUNT - SOI.FOB_AMOUNT)
       END CUSTAMOUNT,
       vi.ZF_VALUE,vi.ZK_VALUE--客户发票金额   
--议付金额  
FROM   SO_SALES_ORDER      SO,
       SO_SALES_ORDER_ITEM SOI,
       CD_DEPARTMENT       D,
       VI_ORDER_ITEM_FEE   VI
WHERE  SO.ORDER_CODE = SOI.ORDER_CODE
AND    SO.FACTORY_CODE = D.DEPT_CODE(+)
AND    SO.ORDER_CODE = VI.ORDER_CODE
AND    SOI.ORDER_ITEM_LINECODE = VI.ORDER_ITEM_LINECODE
AND    D.DEPT_TYPE = '0'

