SELECT S.ORDER_CODE, --订单号
       S.INVOICE_NUM, --发票号
       S.ORDER_SHIP_DATE, --出运期
       SL.ITEM_NAME_EN AS ITEM_NAME_CN, --出运方式
       S.ORDER_PO_CODE, --PO  
       '' AS ORDER_TYPE, --订单类型  
       AL.CONTAINERS AS LOADING_BOX_CODE, --集装箱号
       AL.PACKING_LIST_ID, --ACT_PACKING_LIST表主键
       AL.DESC_GOODS AS PROD_MODEL,
       AL.QUANTITY AS PROD_QUANTITY,
       AL.HAIER_MODEL,
       AL.CUSTOMER_MODEL,
       AL.SIMPLE_CODE,
       AL.WEIGHT AS GROSS_WEIGHT,
       'G/W:' || DECODE(AL.WEIGHT, '', 0, AL.WEIGHT) || ' KGS' AS GROSS_WEIGHT_STRING,
       DECODE(AL.UNIT, '', 'PC', AL.UNIT) AS UNIT,
       AL.NET_WEIGHT AS NET_WEIGHT,
       AL.ITEM_ID,
       AL.BOOK_CODE
FROM   SO_SALES_ORDER S
LEFT   JOIN SYS_LOV SL
ON     (SL.ITEM_CODE = S.ORDER_SHIPMENT AND SL.ITEM_TYPE = '7')
JOIN   ACT_PACKING_LIST AL
ON     S.ORDER_CODE = AL.ORDER_NUM
LEFT   JOIN SO_SALES_ORDER_ITEM SOI
ON     (S.ORDER_CODE = SOI.ORDER_CODE AND SOI.ORDER_ITEM_ID = AL.ITEM_ID)
LEFT   JOIN CD_MATERIAL MM
ON     MM.MATERIAL_CODE = SOI.MATERIAL_CODE
WHERE  AL.BOOK_CODE = #{BOOKCODE}
ORDER  BY S.ORDER_CODE
